# Generated by Django 6.0.2 on 2026-03-02 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sport_name", models.CharField(max_length=100)),
                ("intensity_level", models.IntegerField(default=1)),
                ("duration_each_time", models.IntegerField(default=30)),
                ("experience_points", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("streak", models.IntegerField(default=0)),
                ("last_checkin", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HabitCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("xp_gained", models.IntegerField()),
                (
                    "user_habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.userhabit",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_habit", "date")},
            },
        ),
    ]
