# Generated by Django 6.0.3 on 2026-03-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhabit',
            name='sport_name',
        ),
        migrations.AddField(
            model_name='userhabit',
            name='habit_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userhabit',
            name='sport_type',
            field=models.CharField(default='Running', max_length=50),
            preserve_default=False,
        ),
    ]
