# Generated by Django 6.0.3 on 2026-03-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhabit',
            name='sport_type',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
