# Generated by Django 6.0.2 on 2026-03-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_remove_userhabit_sport_name_userhabit_habit_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitcheckin",
            name="duration",
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
